## Site
darkmode: true
repository: ngoanh2n/ngoanh2n.github.io
favicon: assets/favicon.ico

## Personal info
name: Ho Huu Ngoan
# phone: 098-871-4494
title: Automation Test Engineer
email: ngoanh2n@gmail.com
website: https://ngoanh2n.github.io/blog

## Social links
twitter_username: ngoanh2n
github_username:  ngoanh2n
linkedin_username: ngoanh2n

## Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
google_analytics: "UA-00000000-0"

## About Section
# about_title: About Me
about_profile_image: assets/ngoanh2n.jpg
about_content: |
  Hello, world! My name is Ho Huu Ngoan and I am a Automation Test Engineer from Ho Chi Minh City, Vietnam.
  I graduated in 2015 with a bachelor’s degree in Software Engineering from FPT University.
  I have been in the field for over 6 years.
  Besides, I also started to know the blog sharing knowledge about 
  Automation Test at <a href='/blog' target='_blank'>https://ngoanh2n.github.io/blog</a>

## Section Titles
projects_title: Projects
experience_title: Experience
educaton_title: Education
skills_title: Skills
skills_dev_title: Development Skills

## More Section
# more_title: A Little More About Me
# more_content: |
  # Alongside my interests in coding some of my other interests and hobbies are:

## Footer
footer_show_references: true

## Build settings
remote_theme: sproogen/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
